### ISSUE TITLE
Checkbox are invisible

### ISSUE THREAD

**Issue by bruno-robert** [subtheme-dev/atom-one#5]
**Describe the bug**
Checkboxes in any interface are invisible.

**To Reproduce**
- Install Theme
- Navigate to settings
- find a setting field with a checkbox

**Screenshots**
Atome One Theme
![Screenshot 2021-09-07 at 13 09 17@2x](https://user-images.githubusercontent.com/14978263/132384466-51910c0b-c7ce-4745-89ed-17dca26ffc37.png)

Darkula Theme
![Screenshot 2021-09-07 at 13 09 33@2x](https://user-images.githubusercontent.com/14978263/132384475-3ba63750-5b6c-46e7-aa5c-527c6fa0b219.png)

**Application:**
PyCharm 2021.2.1 Professional

**OS:** 
macos BigSur (11.5.2)

**Atom One Version:**
1.3.1

**Comment by Sithell** [comment]
I have the same problem

**Comment by espositocode** [comment]
Fixed in 1.4, which should be available in a few days. Let me know if you are still seeing issues with checkboxes. Thanks.

https://plugins.jetbrains.com/plugin/14799-atom-one-theme/versions/stable/137395
