### ISSUE TITLE
[Dark] Initial selection in dropdowns have incorrect background colour

### ISSUE THREAD

**Issue by nfourtythree** [subtheme-dev/atom-one#7]
**Describe the bug**
When something like an autocompletion dropdown appears the initially selected item has a light background colour making the text impossible to read.

Using the keys to navigate returns the background colour to the correct darker version.

**Screenshots**
![](https://p191.p3.n0.cdn.getcloudapp.com/items/DOu4P0g2/1ec78607-ae93-4664-b740-893d8ec93d8c.png?v=fb9ed5c15cdfe1ec2eff808a30e78ac2)

**Application:**
PHPstorm 2022.1

**Comment by Masterlovsky** [comment]
IDEA and Pycharm have the same problem

> **Describe the bug** When something like an autocompletion dropdown appears the initially selected item has a light background colour making the text impossible to read.
> 
> Using the keys to navigate returns the background colour to the correct darker version.
> 
> **Screenshots** ![](https://camo.githubusercontent.com/a8422011be7e5a13874eaf48486ebe89a5ef93db62c9196c53ce57068d7bbd2f/68747470733a2f2f703139312e70332e6e302e63646e2e676574636c6f75646170702e636f6d2f6974656d732f444f7534503067322f31656337383630372d616539332d343636342d623734302d3839336438656339336438632e706e673f763d6662396564356331356364666531656332656666383038613330653738616332)
> 
> **Application:** PHPstorm 2022.1

**Comment by espositocode** [comment]
I pushed out a compatibility fix for 2022.x. Can you try the latest and see if that fixes the issue: https://plugins.jetbrains.com/plugin/14799-atom-one-theme/versions/stable/173510

**Comment by nfourtythree** [comment]
@espositocode this looks like it has fixed the issue.

![](https://p191.p3.n0.cdn.getcloudapp.com/items/JruOrYLd/d8569c60-5b4d-4c5c-8e4c-2f60b6fa6fe2.png?v=56fc6e27365a97286e0ee08eace225f8)

Thanks!
