### ISSUE TITLE
[Dark] Selected text is invisible

### ISSUE THREAD

**Issue by vasilev-alex** [subtheme-dev/atom-one#8]
**Describe the bug**
The selected text is invisible

**To Reproduce**
1. Open any project
2. Try to search for some value
3. Select the text in any input

**Screenshots**
<img width="331" alt="Screenshot 2022-04-28 at 19 53 28" src="https://user-images.githubusercontent.com/4973437/165804874-b5277e29-1590-4877-9359-bd4dc6a75fb8.png">

**Application:**
WebStorm  2022.1

**Comment by espositocode** [comment]
Can you try the latest and see if that fixes the issue: https://plugins.jetbrains.com/plugin/14799-atom-one-theme/versions/stable/173510

**Comment by vasilev-alex** [comment]
@espositocode seems to be fine now. Thanks!
